services:

  boinc:
    image: boinc/client:${BOINC_VERSION:-latest}
    container_name: ${BOINC_CONTAINER_NAME:-boinc}
    restart: ${RESTART_POLICY:-unless-stopped}
    env_file:
      - .env
    network_mode: host
    pid: host
    volumes:
      - /opt/appdata/boinc:/var/lib/boinc
    deploy:
      resources:
        limits:
          memory: ${WORDPRESS_MEM_LIM:-4G}
          cpus: ${WORDPRESS_CPU_LIM:-4}
    environment:
      - BOINC_GUI_RPC_PASSWORD=${BOINC_GUI_RPC_PASSWORD}
      - BOINC_PROJECTS=https://www.worldcommunitygrid.org/
      - BOINC_PROJECT_KEYS=${BOINC_PROJECT_KEYS}

